# Generated by Django 6.0.6 on 2026-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
